server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /health {
        proxy_pass http://host.docker.internal:5000;
    }

    location /load {
        proxy_pass http://host.docker.internal:5000;
    }

    location /api {
        proxy_pass http://host.docker.internal:5000;
    }

    location /chat {
        proxy_pass http://host.docker.internal:5000;
    }

    location /upload {
        proxy_pass http://host.docker.internal:5000;
    }
}